// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghvzgzmurgqwfdgixeun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdodnpnem11cmdxd2ZkZ2l4ZXVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDE0MTIsImV4cCI6MjA2MzkxNzQxMn0.375OJAZiAgyOj9uocAvT8WfqeduvFgW7oTQy7eY3i0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);